//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq在EF中的Lambda表达式方法
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int Id { get; set; }
        public string stuID { get; set; }
        public string ClassName { get; set; }
        public string ClassNum { get; set; }
    }
}
