//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 爬虫dome
{
    using System;
    using System.Collections.Generic;
    
    public partial class carinfo
    {
        public int id { get; set; }
        public string brand { get; set; }
        public string title { get; set; }
        public int price { get; set; }
        public byte cartype { get; set; }
        public bool auto { get; set; }
        public int displacement { get; set; }
        public byte age { get; set; }
        public int mileage { get; set; }
        public int emissions { get; set; }
        public string color { get; set; }
        public string grade { get; set; }
        public string MOT { get; set; }
        public string Insurance { get; set; }
        public string structure { get; set; }
        public string engine { get; set; }
        public string transmission { get; set; }
        public string drivingmode { get; set; }
        public string fueltype { get; set; }
        public string consumption { get; set; }
        public string licensi { get; set; }
    }
}
